### ISSUE TITLE
Failing build on Bioconductor

### ISSUE THREAD

**Issue by llrs** [YuLab-SMU/GOSemSim#29]
Hi, there seems to be a problem with the information content calculation on Bioconductor both release and devel.

```
Expecting a string vector: [type=logical; required=STRSXP].
```
Hope you manage to fix it soon, as it is affecting other packages like BioCor. 

I created a reproducible example at https://github.com/llrs/BioCor/issues/28, hope this helps

**Comment by GuangchuangYu** [comment]
https://bioconductor.org/checkResults/3.11/bioc-LATEST/GOSemSim/
https://bioconductor.org/checkResults/3.12/bioc-LATEST/GOSemSim/

It seems OK now.

**Comment by llrs** [comment]
Great, maybe there was some change on the builders. Hope it doesn't bit us again.
