### ISSUE TITLE
Is it possible to run in parallel?

### ISSUE THREAD

**Issue by snijesh** [YuLab-SMU/GOSemSim#38]
I have a long list of genes stored in `data$ID`. I want to calculate semantic similarty using Wang measure as follows.
```result = mgeneSim(data$ID, semData=hsGO2, measure="Wang",combine="BMA",verbose=FALSE)```

How do I parallelize the same code to generate the results with shorter time?

**Comment by qibaiqi** [comment]
> I have a long list of genes stored in `data$ID`. I want to calculate semantic similarty using Wang measure as follows. `result = mgeneSim(data$ID, semData=hsGO2, measure="Wang",combine="BMA",verbose=FALSE)`
> 
> How do I parallelize the same code to generate the results with shorter time?

Sorry to tell you that GOSemSim package don't support parallel calculation for now.

**Comment by snijesh** [comment]
GOSemSim package don't support parallel calculation for now.
